export const CREATE_NEW_GROUP = "CREATE_NEW_GROUP";
export const GET_EXISTING_GROUPS = "GET_EXISTING_GROUPS";
export const CREATE_NEW_HABIT = "CREATE_NEW_HABIT";
export const GET_EXISTING_HABITS = "GET_EXISTING_HABITS";
